[WinEventLog://Security]
disabled = 0
index = endpoint
renderXml = true

[WinEventLog://System]
disabled = 0
index = endpoint
renderXml = true

[WinEventLog://Microsoft-Windows-Sysmon/Operational]
disabled = 0
index = endpoint
renderXml = true
current_only = 0
checkpointInterval = 5
